ALL-438 - next release prep - reuse metadata

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -86,11 +86,6 @@ jobs:
         run: |
           git config --local user.name github-actions
           git config --local user.email github-actions@github.com
-      - name: Get package version
-        id: get_version
-        run: |
-          version=$(jq -r '.version' package.json)
-          echo "PKG_VERSION=$version" >> $GITHUB_ENV
       - name: Get latest release
         id: get_latest_release
         run: |
@@ -98,21 +93,21 @@ jobs:
           echo "LATEST_RELEASE_TAG=$latest_tag" >> $GITHUB_ENV
       - name: Ensure package version is updated
         run: |
-          [ "${{env.PKG_VERSION}}" = "${{env.LATEST_RELEASE_TAG}}" ] && echo "Error: Package version is the same as the latest release" && exit 1 || exit 0
+          [ "${{needs.metadata.outputs.package_version}}" = "${{env.LATEST_RELEASE_TAG}}" ] && echo "Error: Package version is the same as the latest release" && exit 1 || exit 0
       - name: Get release notes
         id: get_release_notes
         uses: ffurrer2/extract-release-notes@v1
       # TAG the repo
-      - name: Create tag ${{env.PKG_VERSION}}
+      - name: Create tag ${{needs.metadata.outputs.package_version}}
         uses: rickstaa/action-create-tag@v1
         with:
-          tag: "${{ env.PKG_VERSION }}"
+          tag: "${{needs.metadata.outputs.package_version}}"
       - name: "Create a GitHub release v${{ steps.package-version.outputs.current-version }}"
       # Create release using the tag above
         uses: ncipollo/release-action@v1
         with:
-          tag: "${{ env.PKG_VERSION }}"
-          name: "${{ env.PKG_VERSION }}"
+          tag: "${{needs.metadata.outputs.package_version}}"
+          name: "${{needs.metadata.outputs.package_version}}"
           body: |
             ${{ steps.get_release_notes.outputs.release_notes }}
   npm:
