Fail PR if pkg version not updated

diff --git a/.github/workflows/release-pr.yaml b/.github/workflows/release-pr.yaml
--- a/.github/workflows/release-pr.yaml
+++ b/.github/workflows/release-pr.yaml
@@ -11,18 +11,26 @@ jobs:
     steps:
       - name: Checkout current
         uses: actions/checkout@v3
-      - name: Calculate changelog hash
+      - name: Get state current
         run: |
           hash=$(sha1sum CHANGELOG.md | cut -f1 -d' ')
+          version=$(jq -r '.version' package.json)
+          echo "pr_pkg_version=$version" >> $GITHUB_ENV 
           echo "pr_changelog_hash=$hash" >> $GITHUB_ENV
       - name: Checkout master
         uses: actions/checkout@v3
         with:
           ref: master
-      - name: Calculate changelog master
+      - name: Get state master
         run: |
           hash=$(sha1sum CHANGELOG.md | cut -f1 -d' ')
+          version=$(jq -r '.version' package.json)
+          echo "master_pkg_version=$version" >> $GITHUB_ENV
           echo "master_changelog_hash=$hash" >> $GITHUB_ENV
       - name: Ensure changelog updated
         run: |
           [ "${{ env.pr_changelog_hash }}" = "${{ env.master_changelog_hash }}" ] && echo "Error: no changes in changelog detected for the release" && exit 1 || exit 0  
+      - name: Ensure package version updated
+        run: |
+           [ "${{ env.pr_pkg_version }}" = "${{ env.master_pkg_version }}" ] && echo "Error: package version not updated" && exit 1 || exit 0
+          
